export * from './cliente.module';
export * from './app-routing-cliente';
export * from './cliente-alterar';
export * from './cliente-depositar';
export * from './cliente-extrato';
export * from './cliente-home';
export * from './cliente-saque';
export * from './cliente-transferencia';
export * from './Utils';